CREATE TABLE employees1 (
	EMP_NO INT(11) NOT NULL
	,BIRTH_DATE DATE NOT NULL
	,FIRST_NAME VARCHAR(14) NOT NULL
	,LAST_NAME VARCHAR(16) NOT NULL
	,GENDER ENUM('M','F')
	,HIRE_DATE DATE
	,CONSTRAINT PK_EMPLOYEES_EMP_NO PRIMARY KEY(EMP_NO)
);


CREATE TABLE salaries1 (
	EMP_NO INT(11) NOT NULL
	,SALARY INT(11) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES_FROM_DATE PRIMARY KEY(FROM_DATE, EMP_NO)
);




CREATE TABLE titles1 (
	EMP_NO INT(11) NOT NULL
	,TITLE VARCHAR(50) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES_FROM_DATE PRIMARY KEY(FROM_DATE, TITLE, EMP_NO)
);

CREATE TABLE dept_emp1 (
	EMP_NO INT(11) NOT NULL
	,DEPT_NO CHAR(4) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES_FROM_DATE PRIMARY KEY(DEPT_NO, EMP_NO)
);
CREATE INDEX EMP_NO ON dept_emp1(EMP_NO);
CREATE INDEX DEPT_NO ON dept_emp1(DEPT_NO);

ALTER TABLE dept_emp1
ADD FOREIGN KEY (DEPT_NO)
REFERENCES departments1(DEPT_NO);


ALTER TABLE dept_emp1
ADD FOREIGN KEY (EMP_NO)
REFERENCES employees1(EMP_NO);

CREATE TABLE departments1 (
	DEPT_NO CHAR(4) NOT NULL
	,DEPT_NAME VARCHAR(40) NOT NULL
	,FROM_DATE DATE NOT NULL
	,TO_DATE DATE NOT NULL
	,CONSTRAINT PK_EMPLOYEES_FROM_DATE PRIMARY KEY(DEPT_NO)
);

ALTER TABLE employees1 ADD COLUMN HIRE_DATE DATE NOT NULL;
ALTER TABLE employees1 DROP COLUMN HIRE_DATE;

CREATE INDEX EMP_NO ON salaries1(EMP_NO);
CREATE INDEX EMP_NO ON titles1(EMP_NO);

ALTER TABLE titles1
ADD FOREIGN KEY (EMP_NO)
REFERENCES employees1(EMP_NO);

ALTER TABLE salaries1
ADD FOREIGN KEY (EMP_NO)
REFERENCES employees1(EMP_NO);